### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by ghost** [pklink/ppma#34]
All of my data stored in the database has a password. But when I try to access data by using PPMA'm having trouble with blank lines.

This is a databese: https://yadi.sk/d/SEkdsKTuYmgAt
This is a PPMA interface: https://yadi.sk/d/QUd7hEeNYmgfU

There are too many passwords. There is only one reserve. Produce your solution!

**Comment by DanClarke-io** [comment]
Hello, we're still having issues with this in the latest version (0.6.0), empty boxes because of incomplete JSON response, see below.
<img width="1430" alt="screen shot 2018-01-26 at 16 26 48" src="https://user-images.githubusercontent.com/6248551/35449720-bc47d4c6-02b5-11e8-8ae0-3b4d1c53b766.png">

**Comment by DanClarke-io** [comment]
For reference to my issue above, this was caused by (for some reason) the encryption key being NULL.

As we're a UK company I've just added in a check if the decrypted password can be parsed by htmlentities, and if not, to then try the NULL encryption key as below:

        public function decrypt($text)
        {

                $item = Yii::app()->securityManager->decrypt($text, $this->encryptionKey);
                if(htmlentities($item)) { return $item; }
                else { return $item = Yii::app()->securityManager->decrypt($text, NULL); }
        }

Obviously this does remove some level of security for us, but until we can pin down the original issue (why was the password encrypted with NULL?) this works for us.
Thanks to @cicero44bc for his help on this.
