### ISSUE TITLE
RFE: Make entry name a link

### ISSUE THREAD

**Issue by oddsocks1024** [pklink/ppma#52]
Could the entry name be made a link as a convenience. It could either bring up the settings for the entry or go to the website, whichever seems to make the most sense.

**Comment by XaRz** [comment]
Oh thanks. This is highly needed. Because in big screens the buttons are too small. Perhaps you must make bigger? (i'm in a mac 27" screen) Look the general view. Perhaps you can make the font/views responsive (and bigger texts obviously)
![passwordmanager](https://cloud.githubusercontent.com/assets/6230850/13978717/85b6973a-f0d3-11e5-89a0-66ecf04757f9.png)
